// <auto-generated />
namespace PG_Arts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class commande : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commande));
        
        string IMigrationMetadata.Id
        {
            get { return "202206071608203_commande"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
